import { DAY_ONE_ACTIONS_V01 } from './day-one-actions-v01.js';
import { KEY_OBJECT_CUES_V1 } from './key-object-cues-v1.js';

function deepFreeze(value) {
  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
  Object.freeze(value);
  for (const child of Object.values(value)) deepFreeze(child);
  return value;
}

export const DAY_ONE_INTERACTION_IDS = deepFreeze({
  woodlot: 'day-one-woodlot',
  fishingSpot: 'day-one-fishing-spot',
  campfire: 'day-one-campfire',
  garden: 'day-one-garden',
  shelter: 'day-one-shelter',
});

export const DAY_ONE_V01 = deepFreeze({
  id: 'day-one-v01',
  title: 'A Place for Tonight',
  ids: DAY_ONE_INTERACTION_IDS,

  events: {
    stewardMet: 'steward-lumen-met',
    afternoonComplete: 'first-afternoon-complete',
    ledgerSigned: 'community-ledger-signed',
  },

  actions: DAY_ONE_ACTIONS_V01,

  ledgerRecord: {
    id: 'day-one-neighborly-account',
    title: 'COMMUNITY LEDGER · TODAY’S ACCOUNT',
    labels: {
      wood: 'WOOD GATHERED',
      fish: 'PONDFISH CAUGHT',
      fire: 'CAMPFIRE LIT',
      cooked: 'SUPPER PREPARED',
      eaten: 'SUPPER TAKEN',
      garden: 'SEED BED',
      shelter: 'SHELTER BRACED',
    },
    awaiting: 'AWAITING',
    recorded: 'RECORDED',
    planted: 'PLANTED',
    watered: 'PLANTED + WATERED',
    signature: 'Neighbor on file',
    signatureLabel: 'Account kept under',
    detail: 'The ink keeps pace without a clerk nearby.',
    actionLabel: 'Close the Ledger',
    altered: false,
  },

  anchors: {
    camp: { x: -24.2, y: 0, z: 6.25 },
    campRecovery: { x: -29.3, y: 0.9, z: 3.8 },
    woodlot: { x: -32.3, y: 0, z: -0.5 },
    fishingSpot: { x: 16.4, y: 0.25, z: 4 },
    campfire: { x: -24.5, y: 0.2, z: 2.4 },
    garden: { x: -27, y: 0, z: 6.8 },
    shelter: { x: -31.5, y: 0, z: 4.8 },
  },

  tuning: {
    meters: {
      max: 100,
      startingEnergy: 82,
      startingNourishment: 72,
      recoveryEnergy: 70,
      recoveryNourishment: 55,
    },
    startingInventory: {
      wood: 0,
      rawFish: 0,
      cookedFish: 0,
      seeds: 1,
    },
    startingCoins: 8,
    doctorFee: 4,
    woodPerChop: 2,
    woodInventoryLimit: 10,
    fishCatchLimit: 3,
    fireWoodCost: 1,
    shelterWoodCost: 4,
    mealRecovery: {
      energy: 45,
      nourishment: 48,
    },
    labor: {
      chop: { energy: 16, nourishment: 6 },
      fish: { energy: 14, nourishment: 5 },
      plant: { energy: 6, nourishment: 2 },
      water: { energy: 8, nourishment: 3 },
      repairShelter: { energy: 18, nourishment: 7 },
    },
    requirements: {
      woodGathered: 6,
      mealsEaten: 1,
      gardenPlanted: true,
      gardenWatered: true,
      shelterRepaired: true,
    },
  },

  prompts: {
    chop: 'Chop fallen wood',
    woodFull: 'Your arms are full of wood',
    fish: 'Fish the pond',
    fishFinished: 'Let the pond settle',
    lightFire: 'Light the campfire (1 wood)',
    needFireWood: 'Gather 1 wood for the campfire',
    cookFish: 'Cook the fish',
    eatFish: 'Eat the cooked fish',
    warmHands: 'Warm your hands by the fire',
    plant: 'Plant the seed',
    needSeed: 'Find a seed to plant',
    water: 'Water the planted seed',
    gardenDone: 'The little garden is settled',
    repairShelter: 'Brace the shelter (4 wood)',
    needShelterWood: 'Gather 4 wood for the shelter',
    shelterDone: 'The shelter is ready for tonight',
  },

  objectives: {
    meetSteward: {
      id: 'day-one-meet-steward',
      label: 'A place kept warm',
      text: 'Meet the steward who kept the gate open for you.',
      title: 'A place kept warm',
      detail: 'Meet the steward who kept the gate open for you.',
      target: { kind: 'interactable', id: 'steward-8914' },
    },
    gatherWood: {
      id: 'day-one-gather-wood',
      label: 'What the forest gives',
      text: 'Gather 6 wood for a fire and a sturdier shelter.',
      title: 'What the forest gives',
      detail: 'Gather 6 wood for a fire and a sturdier shelter.',
      cue: KEY_OBJECT_CUES_V1.camp,
      target: { kind: 'interactable', id: DAY_ONE_INTERACTION_IDS.woodlot },
    },
    catchFish: {
      id: 'day-one-catch-fish',
      label: 'Supper from the pond',
      text: 'Catch one fish in the pond.',
      title: 'Supper from the pond',
      detail: 'Catch one fish in the pond.',
      target: { kind: 'interactable', id: DAY_ONE_INTERACTION_IDS.fishingSpot },
    },
    lightFire: {
      id: 'day-one-light-fire',
      label: 'A little warmth',
      text: 'Use 1 wood to light the campfire.',
      title: 'A little warmth',
      detail: 'Use 1 wood to light the campfire.',
      cue: KEY_OBJECT_CUES_V1.camp,
      target: { kind: 'interactable', id: DAY_ONE_INTERACTION_IDS.campfire },
    },
    cookFish: {
      id: 'day-one-cook-fish',
      label: 'Supper from the pond',
      text: 'Cook your fish over the campfire.',
      title: 'Supper from the pond',
      detail: 'Cook your fish over the campfire.',
      cue: KEY_OBJECT_CUES_V1.camp,
      target: { kind: 'interactable', id: DAY_ONE_INTERACTION_IDS.campfire },
    },
    eatFish: {
      id: 'day-one-eat-fish',
      label: 'Take care of yourself',
      text: 'Eat the cooked fish to restore nourishment and energy.',
      title: 'Take care of yourself',
      detail: 'Eat the cooked fish to restore nourishment and energy.',
      cue: KEY_OBJECT_CUES_V1.camp,
      target: { kind: 'interactable', id: DAY_ONE_INTERACTION_IDS.campfire },
    },
    plantSeed: {
      id: 'day-one-plant-seed',
      label: 'Something for tomorrow',
      text: 'Plant your seed in the garden bed beside camp.',
      title: 'Something for tomorrow',
      detail: 'Plant your seed in the garden bed beside camp.',
      cue: KEY_OBJECT_CUES_V1.camp,
      target: { kind: 'interactable', id: DAY_ONE_INTERACTION_IDS.garden },
    },
    waterSeed: {
      id: 'day-one-water-seed',
      label: 'Something for tomorrow',
      text: 'Water the planted seed.',
      title: 'Something for tomorrow',
      detail: 'Water the planted seed.',
      cue: KEY_OBJECT_CUES_V1.camp,
      target: { kind: 'interactable', id: DAY_ONE_INTERACTION_IDS.garden },
    },
    gatherShelterWood: {
      id: 'day-one-gather-shelter-wood',
      label: 'A roof for tonight',
      text: 'Gather enough wood to brace the makeshift shelter.',
      title: 'A roof for tonight',
      detail: 'Gather enough wood to brace the makeshift shelter.',
      cue: KEY_OBJECT_CUES_V1.camp,
      target: { kind: 'interactable', id: DAY_ONE_INTERACTION_IDS.woodlot },
    },
    repairShelter: {
      id: 'day-one-repair-shelter',
      label: 'A roof for tonight',
      text: 'Use 4 wood to brace the makeshift shelter.',
      title: 'A roof for tonight',
      detail: 'Use 4 wood to brace the makeshift shelter.',
      cue: KEY_OBJECT_CUES_V1.camp,
      target: { kind: 'interactable', id: DAY_ONE_INTERACTION_IDS.shelter },
    },
    signLedger: {
      id: 'day-one-sign-ledger',
      label: 'The first town courtesy',
      text: 'Enter your name in the Community Ledger before settling your plot.',
      title: 'The first town courtesy',
      detail: 'Enter your name in the Community Ledger before settling your plot.',
      cue: KEY_OBJECT_CUES_V1.ledger,
      target: { kind: 'interactable', id: 'ledger' },
    },
  },

  messages: {
    inactive: 'The Ledger must know your name before it can keep the afternoon.',
    busy: 'Take a breath. One thing at a time.',
    actionChanged: 'Something changed before you could finish. Take another look.',
    wood: 'You split two dry branches. The Ledger records the bundle.',
    woodFull: 'You cannot carry more wood just now.',
    fish: 'A pondfish takes the line. The Ledger records one catch.',
    fishFinished: 'The pond has given enough for one afternoon.',
    fire: 'The kindling catches. The Ledger records one fire.',
    needFireWood: 'The fire ring needs one piece of wood.',
    cookedFish: 'The fish crisps over the coals. The Ledger records supper prepared.',
    ateFish: 'A hot meal restores your nourishment and energy. The Ledger records supper taken.',
    nothingToCook: 'The fire is warm, but there is nothing to cook.',
    planted: 'One seed settles into the dark soil. The Ledger records something begun.',
    needSeed: 'You do not have a seed to plant.',
    watered: 'The soil darkens. The Ledger records the seed bed tended.',
    gardenDone: 'The seed bed is planted and watered.',
    shelter: 'The shelter stands firm. The Ledger records camp as settled. If exhaustion takes you now, you’ll wake here.',
    needShelterWood: 'You need four pieces of wood to brace the shelter.',
    shelterDone: 'The shelter is already ready for tonight.',
    complete: 'The Ledger closes the afternoon’s account. The Town Bell waits on the hill.',
    passedOutGatePaid: 'You wake beside Thornvale’s front gate. Until your shelter is repaired, this is where the town returns you. The doctor’s fee was {fee} coins.',
    passedOutGateDebt: 'You wake beside Thornvale’s front gate. Until your shelter is repaired, this is where the town returns you. You paid {paid} coins and now owe {debt} more.',
    passedOutShelterPaid: 'You wake beside your repaired shelter. The doctor’s fee was {fee} coins.',
    passedOutShelterDebt: 'You wake beside your repaired shelter. You paid {paid} coins and now owe {debt} more.',
  },
});
